# Generated by Django 3.2.2 on 2021-05-17 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradename', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('jobdetail', models.TextField()),
                ('wage', models.IntegerField()),
                ('currentapplicant', models.IntegerField()),
            ],
        ),
    ]
