# Generated by Django 3.2.2 on 2021-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0002_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='isapply',
            field=models.BooleanField(default=False),
        ),
    ]
