# Generated by Django 3.2.3 on 2021-05-22 06:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0005_rename_commnet_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blog_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='curd_app.store'),
        ),
    ]
