# Generated by Django 3.2.3 on 2021-05-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0006_alter_comment_blog_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog_id',
            new_name='store_id',
        ),
    ]
