# Generated by Django 3.2.3 on 2021-05-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0007_rename_blog_id_comment_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
