# Generated by Django 3.2.3 on 2021-05-22 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curd_app', '0008_blog_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
